# Generated by Django 3.1.7 on 2021-04-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='admin',
            new_name='administrador',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='prop',
            new_name='propietario',
        ),
    ]
