# Generated by Django 3.1.7 on 2021-04-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210411_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='propietario',
            new_name='propietarioAdministrador',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nomeFantasia',
            field=models.CharField(default=True, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
