# Generated by Django 3.1.7 on 2021-05-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210503_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='cavaloMecanico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='empresa',
            field=models.ForeignKey(db_column='empresa', default=3, on_delete=django.db.models.deletion.CASCADE, to='login.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculos',
            name='inicialKm',
            field=models.DecimalField(decimal_places=2, default=1000.21, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculos',
            name='marcaVeiculo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculos',
            name='motorista',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculos',
            name='tipoVeiculo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='propietario',
            field=models.CharField(max_length=150),
        ),
    ]
