# Generated by Django 3.1.7 on 2021-05-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210513_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='fabricado',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
