# Generated by Django 3.1.7 on 2021-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_veiculos_fabricado'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='cargo',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
