# Generated by Django 3.1.7 on 2021-05-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
